apiVersion: monitoring.coreos.com/v1
kind: Grafana
metadata:
  name: rag-grafana
  namespace: rag-platform
spec:
  replicas: 1
  dashboardLabelSelector:
    matchLabels:
      team: rag-platform
  config:
    log:
      level: info
    analytics:
      check_for_updates: false