apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: rag-platform
spec:
  selector:
    app: tempo
  ports:
    - port: 3200
      targetPort: 3200
      name: http
    - port: 4317
      targetPort: 4317
      name: grpc
    - port: 4318
      targetPort: 4318
      name: http-otlp
  type: ClusterIP